Edit profile  and sign up functionality completed
BC-MAY-21-ROR/proyecto-final-pf-n21-t3 pull request #15
Opened 2022-02-02 06:51 UTC by IrenehMDev

Co-authored-by: DerekAyala <derek.ayala12345@hotmail.com>

# Description
- Added last_name field to the user table from migration.
- Added required fields to Sign Up's view (Devise).
- Added required fields to Edit Profile's view (Devise) like to Sign Up's view.
- Implemented just sign up and edit profile functionality.
- Generated Devise Controllers.
 
  ## Screenshots 
![image](https://user-images.githubusercontent.com/50089408/152101228-cf102b75-32c3-44e3-b21f-313ebd01722c.png)

![image](https://user-images.githubusercontent.com/50089408/152101263-872c1841-fc70-4c3a-9e79-0b7ff64d5fe0.png)

![image](https://user-images.githubusercontent.com/50089408/152101456-7807d3f6-47a7-4af9-9cc6-297f9592b2c7.png)

![image](https://user-images.githubusercontent.com/50089408/152101475-2060c811-85ec-4028-86e4-c59414a3d6df.png)

2022-02-02 17:54 UTC, JuanequeX requested changes

2022-02-02 17:54 UTC, JuanequeX commented on app/controllers/application_controller.rb
> +        end
Please review this indentation, two spaces are the ideal

2022-02-02 17:54 UTC, JuanequeX commented on app/controllers/users/registrations_controller.rb
> +  # end
This method cannot be useful if you also comment the `end` xd

2022-02-02 18:52 UTC, kevinnio requested changes

2022-02-02 18:52 UTC, kevinnio commented on app/controllers/users/confirmations_controller.rb
> +  # GET /resource/confirmation/new
Is there a reason to have all these comments here? What do you think about removing them?

2022-02-02 18:52 UTC, kevinnio commented on app/views/devise/registrations/new.html.erb
> +    <%= f.select(:gender, options_for_select([['Female','Female'],['Male','Male']])) %>
```suggestion
      <%= f.select(:gender, options_for_select([['Female','Female'],['Male','Male']])) %>
```

2022-02-02 18:52 UTC, kevinnio commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.select(:gender, options_for_select([['Female','Female'],['Male','Male']])) %>
```suggestion
      <%= f.select(:gender, options_for_select([['Female','Female'],['Male','Male']])) %>
```

2022-02-02 18:52 UTC, kevinnio commented on app/controllers/users/registrations_controller.rb
> +     super
Is there any reason to define `#new` here? If this methods just calls `super`, then it's the same as just using the inherited method from `Devise::RegistrationsController`. 🤔

2022-02-03 02:45 UTC, kevinnio approved these changes

2022-02-03 03:30 UTC, YilKanda approved these changes

2022-02-03 05:43 UTC, DerekAyala approved these changes

2022-02-03 21:20 UTC, JuanequeX approved these changes
LGTM

2022-02-03 23:25 UTC, merged