Feature#54 user form design
BC-MAY-21-ROR/proyecto-final-pf-n21-t3 pull request #55
Opened 2022-02-26 01:04 UTC by DerekAyala

# Description
What did you implement/Why did you implement this:
 - design to user edit form with picture functionality.

  ## Screenshots 
User edit form
![Screenshot from 2022-02-25 18-57-25](https://user-images.githubusercontent.com/89038565/155822197-b725cf46-cdc2-4175-91d9-9a9637871226.png)

delete account 
![Screenshot from 2022-02-25 18-57-29](https://user-images.githubusercontent.com/89038565/155822325-114435bd-a4c5-4bcb-abb4-1531a41e6df0.png)

profile view
![Screenshot from 2022-02-25 19-02-41](https://user-images.githubusercontent.com/89038565/155822330-62c26c30-c9aa-423e-bbf0-7767c8152e02.png)

2022-02-26 01:44 UTC, JuanequeX requested changes

2022-02-26 01:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_forms.scss
> +    color: white;
Sort this block

2022-02-26 01:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_forms.scss
> +    gap: 1rem;
sort this block

2022-02-26 01:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_profile.scss
> +    color: black;
Sort it and add extra space between label a and your bracket

2022-02-28 17:38 UTC, JuanequeX approved these changes
LGTM

2022-02-28 17:55 UTC, LuisGomez89 approved these changes

2022-02-28 17:57 UTC, IrenehMDev approved these changes
LGTM

2022-02-28 18:24 UTC, YilKanda approved these changes
LGTM!

2022-02-28 18:30 UTC, merged